#pragma once
#define PREDATOR_SPEED 2
#define PREDATOR_LIFE 40
#define PREDATOR_VISION 6
#define PREY_SPEED 1
#define PREY_LIFE 25
#define PREY_VISION 4
#define STONE_LIFE 0
#define OCEAN_SIZE_X 60
#define OCEAN_SIZE_Y 20
#define OCEAN_NUMBER_OF_PREYS 20
#define OCEAN_NUMBER_OF_PREDATORS 5
#define OCEAN_NUMBER_OF_STONES 5

